name: Build APK

on:
  # auto run on push/merge on master branch
  push:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_POS_API_URL: "https://pc.soberdev.net/"
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "12.x"
          cache: 'gradle'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.9'
          channel: 'stable'
          cache: true
      - name: Get dependencies
        run: flutter pub get
      - name: Build APK
        run: flutter build apk --split-per-abi --obfuscate --release
      - uses: actions/upload-artifact@v2
        with:
          name: release-apks
          path: "build/app/outputs/apk/release/"
